name: Build and Test Calculator App

on:
  push:
    branches: [main]
  pull_request:
    branches: [docker]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
        IMAGE=ghcr.io/${{ github.repository }}:latest
        docker build -t $IMAGE .
        docker push $IMAGE

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pull Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository }}:latest
        docker pull $IMAGE

    - name: Run tests inside container
      run: |
        IMAGE=ghcr.io/${{ github.repository }}:latest
        docker run --rm $IMAGE sh -c "if [ -f program_tests.py ]; then python program_tests.py; else echo 'Test file not found'; exit 1; fi"
