name: Build and Test Calculator App

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ docker ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE=ghcr.io/notproinprogramming/lab_6:latest
        docker build -t $IMAGE .
        docker push $IMAGE

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pull Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository }}:latest
        docker pull $IMAGE

    - name: Run tests inside container
      run: |
        docker run --rm ghcr.io/${{ github.repository }}:latest python program_tests.py
